### ISSUE TITLE
Creation of new repository

### ISSUE THREAD

**Issue by PyMichaelB** [PyMichaelB/rabbitmq-queue-management-docker#2]
Hi @gessnerfl,

I've seen your rabbitmq-queue-management project and I have created a new repo to allow me to build and release Docker images running a containerised version of your project. I wanted to let you know that this is that repo! If you have any questions feel free to reply on this issue. 

All the best,

Michael

**Comment by gessnerfl** [comment]
@michael18781 thanks for letting me know. Great to see that the tool is used by others as well. I can also consider adding docker images in my repo so that images are being updated with each release of the application as well

**Comment by gessnerfl** [comment]
@PyMichaelB with release 1.2.0 docker images are available on https://hub.docker.com/repository/docker/gessnerfl/rabbitmq-queue-management

**Comment by PyMichaelB** [comment]
@gessnerfl Ok great. I'll continue maintaining mine but it's good yours will be available on every release. I've also created a helm chart for Kubernetes deployments which can be found in https://github.com/PyMichaelB/charts.
